const POSTS = {
  POST_LOADING: 'POST_LOADING',
  POST_UPDATE: 'POST_UPDATE',
  POST_ERROR: 'POST_ERROR'
}

const PAGE = {
  CHANGE_PAGE: 'CHANGE_PAGE'
};

const MOVIE = {
  MOVIE_LOADING: 'MOVIE_LOADING',
  MOVIE_UPDATE: 'MOVIE_UPDATE',
  MOVIE_ERROR: 'MOVIE_ERROR',
  MOVIE_NEXT_PAGE: 'MOVIE_NEXT_PAGE'
}

export { POSTS, PAGE, MOVIE }