const POSTS = {
  POST_LOADING: 'POST_LOADING',
  POST_UPDATE: 'POST_UPDATE',
  NEXT_POST: 'NEXT_POST',
  PREVIOUS_POST: 'PREVIOUS_POST',
  POST_ERROR: 'POST_ERROR'
}

const MOVIE = {
  MOVIE_LOADING: 'MOVIE_LOADING',
  MOVIE_UPDATE: 'MOVIE_UPDATE',
  MOVIE_ERROR: 'MOVIE_ERROR',
  MOVIE_NEXT_PAGE: 'MOVIE_NEXT_PAGE'
}

export { POSTS, MOVIE }